name: KtLint Format

on: [pull_request]

jobs:
  ktlint-linting-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: configure java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true
          gradle-version: 7.6
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: debug-lint
        run: ./gradlew lint
      - name: KTlint-format
        run: ./gradlew ktlintformat
